# Generated by Django 4.1.3 on 2022-11-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
